### ISSUE TITLE
How can I solve this problem when install

### ISSUE THREAD

**Issue by NinJa4270** [DeepThought-AI/Holmes#5]
when sudo sh ./Install_cn.sh

```
Error:

#HOLMES environment variables
#log level
HOLMES_LOG_LEVEL=INFO
# use other redis config; default: docker redis://redis:6379/0
# HOLMES_REDIS_URL=redis://127.0.0.1:6379/0
# session encryption string
HOLMES_COOKIE_SECRET=b3da006876108d19dda000134e4025fe
# database encryption string, same with HOLMES_SECRET_KEY, you can change
HOLMES_SECRET_KEY=b3da006876108d19dda000134e4025fe
# use other postgresql database; default docker postgresql://postgres@postgres/postgres
# HOLMES_DATABASE_URL="postgresql://user:pwd@ip/database"
# allow custom js visualizations
HOLMES_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS=True
# Language CN/EN, only ip address ,no
WEB_LANGUAGE=CN
# web server ip address or domain,for ai get database config option. port 5000,same with Docker
WEB_SERVER=127.0.0.1:8338
# api secret key for ai get database config option
DB_API_SECRET_KEY=b3da006876108d19dda000134e4025fe
# web content security policy
HOLMES_CONTENT_SECURITY_POLICY="style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' http: https: data: blob:; object-src 'none'; frame-ancestors 'none';"
# socket dir, need set Localhost ip
REACT_APP_SOCKET_URL=127.0.0.1:8339/chat/
# static file CDN
CDN_DOMAIN=
--------------------------------
下面将开始 通过docker-compose 拉取创建镜像，可能需要60分钟，主要根据你的网络情况，请耐心等待。 
或者，你修改本地docker 镜像源地址，比如更改为阿里云等
[+] Building 159.0s (27/28)                                                                                                 docker:default
 => [server internal] load build definition from Dockerfile                                                                           0.0s
 => => transferring dockerfile: 2.99kB                                                                                                0.0s
 => [server internal] load .dockerignore                                                                                              0.0s
 => => transferring context: 263B                                                                                                     0.0s
 => [server internal] load metadata for docker.io/library/python:3.8.18-slim                                                          1.9s
 => [server internal] load metadata for docker.io/library/node:14.17                                                                  1.9s
 => [server frontend-builder  1/10] FROM docker.io/library/node:14.17@sha256:40aa86fa97c6cb85af15ecdd67798f7578c5c20e8d16f99d5b4f8f1  0.0s
 => => resolve docker.io/library/node:14.17@sha256:40aa86fa97c6cb85af15ecdd67798f7578c5c20e8d16f99d5b4f8f14196a0568                   0.0s
 => [server internal] load build context                                                                                              0.1s
 => => transferring context: 124.77kB                                                                                                 0.1s
 => [server stage-1  1/13] FROM docker.io/library/python:3.8.18-slim@sha256:19e07fa24813e88b04e606772213bd03ba044637cc939a211e28ccf9  0.0s
 => => resolve docker.io/library/python:3.8.18-slim@sha256:19e07fa24813e88b04e606772213bd03ba044637cc939a211e28ccf997a9162a           0.0s
 => CACHED [server stage-1  2/13] RUN useradd --create-home holmes                                                                    0.0s
 => CACHED [server stage-1  3/13] RUN apt-get update                                                                                  0.0s
 => CACHED [server stage-1  4/13] RUN apt-get clean && apt-get update &&   apt-get install -y --no-install-recommends   curl   gnupg  0.0s
 => CACHED [server stage-1  5/13] RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple                        0.0s
 => CACHED [server stage-1  6/13] RUN pip install --upgrade pip                                                                       0.0s
 => [server stage-1  7/13] COPY --chown=holmes . /app                                                                                 0.2s
 => CACHED [server frontend-builder  2/10] RUN npm install --global --force yarn@1.22.19                                              0.0s
 => CACHED [server frontend-builder  3/10] RUN useradd -m -d /frontend holmes                                                         0.0sl
 => CACHED [server frontend-builder  4/10] WORKDIR /frontend                                                                          0.0s
 => CACHED [server frontend-builder  5/10] COPY --chown=holmes package.json yarn.lock .yarnrc /frontend/                              0.0sl
 => CACHED [server frontend-builder  6/10] COPY --chown=holmes client /frontend/client                                                0.0s
 => CACHED [server frontend-builder  7/10] COPY --chown=holmes package.json /frontend/                                                0.0sl
 => CACHED [server frontend-builder  8/10] COPY --chown=holmes webpack.config.js /frontend/                                           0.0s
 => [server frontend-builder  9/10] COPY --chown=holmes .env /frontend/                                                               0.0s
 => [server frontend-builder 10/10] RUN yarn && yarn build                                                                          146.8s
 => [server stage-1  8/13] WORKDIR /app                                                                                               0.0s
 => [server stage-1  9/13] COPY --from=frontend-builder /frontend/client/dist /app/client/dist                                        0.2s
 => [server stage-1 10/13] RUN pip install pip==20.2.4                                                                                1.8s
 => [server stage-1 11/13] RUN if [ "xyes" = "x" ] ; then pip install -r requirements_dev.txt ; fi                                    0.3s
 => ERROR [server stage-1 12/13] RUN pip install -r requirements.txt && pip install -r requirements_ai.txt                            7.7s
------
 > [server stage-1 12/13] RUN pip install -r requirements.txt && pip install -r requirements_ai.txt:
0.400 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
0.650 Collecting Flask==1.1.1
0.717   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94 kB)
0.899 Collecting Jinja2==2.10.3
0.952   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl (125 kB)
1.077 Collecting itsdangerous==1.1.0
1.131   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
1.242 Collecting click==6.7
1.297   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71 kB)
1.471 Collecting MarkupSafe==1.1.1
1.524   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/83/66/ec77a7000486d4d6acb599993b58dc4c97d510e3f2c37b81d31fb7632c4f/MarkupSafe-1.1.1-cp38-cp38-manylinux2014_aarch64.whl (33 kB)
1.606 Collecting pyOpenSSL==19.0.0
1.659   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl (53 kB)
1.744 Collecting httplib2==0.14.0
1.797   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d2/84/f97b9efdb17c9b73e133bdbf2b4bfd09cd0be655e36e3ee3c4bec9095048/httplib2-0.14.0-py3-none-any.whl (94 kB)
1.892 Collecting wtforms==2.2.1
1.946   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9f/c8/dac5dce9908df1d9d48ec0e26e2a250839fa36ea2c602cc4f85ccfeb5c65/WTForms-2.2.1-py2.py3-none-any.whl (166 kB)
2.106 Collecting Flask-RESTful==0.3.7
2.162   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/17/44/6e490150ee443ca81d5f88b61bb4bbb133d44d75b0b716ebe92489508da4/Flask_RESTful-0.3.7-py2.py3-none-any.whl (24 kB)
2.239 Collecting Flask-Login==0.4.1
2.291   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c1/ff/bd9a4d2d81bf0c07d9e53e8cd3d675c56553719bbefd372df69bf1b3c1e4/Flask-Login-0.4.1.tar.gz (14 kB)
2.548 Collecting Flask-SQLAlchemy==2.4.1
2.606   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1e/65/226d95466c75e34e291a76890ed0e27af2e46ab913002847856f11d4d59d/Flask_SQLAlchemy-2.4.1-py2.py3-none-any.whl (17 kB)
2.682 Collecting Flask-Migrate==2.5.2
2.733   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4b/22/d20a105f13c58fe590ef38ac59d5cabc1a917549ea8f90b0ca7b4e84f6be/Flask_Migrate-2.5.2-py2.py3-none-any.whl (13 kB)
2.810 Collecting flask-mail==0.9.1
2.871   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz (45 kB)
3.075 Collecting flask-talisman==0.7.0
3.128   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/88/cd/b4e2be50bfc53607e2359d12899a105a3b18ae68cb6a573d70c535ebeca5/flask_talisman-0.7.0-py2.py3-none-any.whl (12 kB)
3.236 Collecting Flask-Limiter==0.9.3
3.292   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9b/1b/23841342194bdd55e33d85a6f2e023c69d837fb69cee173352b7edba3c1f/Flask-Limiter-0.9.3.tar.gz (82 kB)
3.475 Collecting Flask-WTF==0.14.3
3.527   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/36/a9/8c01171066bd7a524ee005d81bb4a8aa446ab178043a1ad6cb5dc8f0bd83/Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
3.596 Collecting passlib==1.7.1
3.649   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl (498 kB)
3.807 Collecting aniso8601==8.0.0
3.861   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/eb/e4/787e104b58eadc1a710738d4e418d7e599e4e778e52cb8e5d5ef6ddd5833/aniso8601-8.0.0-py2.py3-none-any.whl (43 kB)
3.947 Collecting blinker==1.4
4.003   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz (111 kB)
4.268 Collecting psycopg2==2.8.3
4.320   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz (377 kB)
4.555 Collecting python-dateutil==2.8.0
4.605   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226 kB)
4.751 Collecting pytz>=2019.3
4.803   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
4.934 Collecting PyYAML==5.4
4.985   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b5/fd/15638de2da0a5aa91c095718444624aa565f766fc178249ca6faa372f71a/PyYAML-5.4.tar.gz (174 kB)
5.073   Installing build dependencies: started
7.523   Installing build dependencies: finished with status 'done'
7.524   Getting requirements to build wheel: started
7.651   Getting requirements to build wheel: finished with status 'error'
7.651   ERROR: Command errored out with exit status 1:
7.651    command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpijhzqawr
7.651        cwd: /tmp/pip-install-k8zf91q9/pyyaml
7.651   Complete output (48 lines):
7.651   running egg_info
7.651   writing lib3/PyYAML.egg-info/PKG-INFO
7.651   writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
7.651   writing top-level names to lib3/PyYAML.egg-info/top_level.txt
7.651   Traceback (most recent call last):
7.651     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
7.651       main()
7.651     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
7.651       json_out['return_val'] = hook(**hook_input['kwargs'])
7.651     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
7.651       return hook(config_settings)
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
7.651       return self._get_build_requires(config_settings, requirements=['wheel'])
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
7.651       self.run_setup()
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
7.651       exec(code, locals())
7.651     File "<string>", line 271, in <module>
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
7.651       return distutils.core.setup(**attrs)
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
7.651       return run_commands(dist)
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
7.651       dist.run_commands()
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
7.651       self.run_command(cmd)
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
7.651       super().run_command(command)
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
7.651       cmd_obj.run()
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 321, in run
7.651       self.find_sources()
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
7.651       mm.run()
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 551, in run
7.651       self.add_defaults()
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
7.651       sdist.add_defaults(self)
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
7.651       super().add_defaults()
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
7.651       self._add_defaults_ext()
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
7.651       self.filelist.extend(build_ext.get_source_files())
7.651     File "<string>", line 201, in get_source_files
7.651     File "/tmp/pip-build-env-h6u0s6i5/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
7.651       raise AttributeError(attr)
7.651   AttributeError: cython_sources
7.651   ----------------------------------------
7.651 ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpijhzqawr Check the logs for full command output.
------
failed to solve: process "/bin/sh -c pip install -r requirements.txt && pip install -r requirements_ai.txt" did not complete successfully: exit code: 1
--------------------------------
```

**Comment by wangshiyouyang** [comment]
We have just tested on Mac OS 14+, Ubuntu 20.04+, and Windows WSL 22.04, and did not encounter the corresponding error.
1. Please let us know the environment you are running in, and we will test in the corresponding environment.
2. Alternatively, you can try reinstalling the command using sudo ./Install_cn.sh.

**Comment by jianjun159** [comment]
> > We have just tested on Mac OS 14+, Ubuntu 20.04+, and Windows WSL 22.04, and did not encounter the corresponding error.
> > 
> > 1. Please let us know the environment you are running in, and we will test in the corresponding environment.
> > 2. Alternatively, you can try reinstalling the command using sudo ./Install_cn.sh.
> > 
> > Do not use 127.0.0.1 as the Docker service IP, because Docker uses the local intranet address. It is recommended to use the local intranet address of the host machine instead. Such as 192.168.xxx.xxx
> 
> The same problem occurred when building docker images on computers with macbook pro m1 chips

The cause of this problem are two python depend on the version of the problems, the specific reference issus address: https://github.com/yaml/pyyaml/issues/724
Corresponding solutions: PyYaml upgraded to 6.0, cryptography upgraded to 3.1.1
